// This needs to be added to the app.module.ts to be visible to all components

// This file gets generated by "ng generate service data" command in the main directory of the angular project
import { Injectable } from '@angular/core';

// This is needed for some reason, no explaination given (npm install --save rxjs-compat)
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  // Next 2 lines, dont know how they affect the data share
  private goals = new BehaviorSubject<any>(['Initial Goal!', 'Another Silly goal!']);
  goal = this.goals.asObservable();

  constructor() { }

  // A method that will be callable from any component to change goals
  // shouldnt the param say goals, since we are always passing an array which then will be made as the next value 
  // of this service's goals
  // Look at http://reactivex.io/rxjs/manual/overview.html for better understanding, each function like next(), complete(), error()
  // on the observable class can be caught by someone subscribing and act of each element different by either printing on the screen
  // or pushing to db. here the goal/goals is subcribed to by HomeComponent in the constructor where we define what we do when any action
  // by just updating the goals variable for display
  changeGoal(goal)
  {
      // next probably adds to the BehaviorSubject object which is holding the data to be shared between components
      this.goals.next(goal);
  }
}
